---
image: docker.io/nerzhul/archlinux:2016.10.01
# These are already included in image
# - pacman --noconfirm -S libxml2 jsoncpp curl

stages:
  - codestyle
  - cppcheck
  - build
  - package
  - pages

check:codestyle:
  stage: codestyle
  environment: staging
  script:
    - .gitlab-ci/codestyle_check.sh

check:codestyle:
  stage: cppcheck
  environment: staging
  before_script:
    - pacman --noconfirm -Sy cppcheck
  script:
    - cppcheck --enable=warning,performance godotengine/modules/hotelmanager

.build_template: &build_template
  stage: build
  environment: staging
  artifacts:
    when: on_success
    expire_in: 1 day
  before_script:
    - pacman --noconfirm -Sy scons libxcursor libxinerama libxrandr mesa glu alsa-lib pulseaudio freetype2 > /dev/null

build:gcc6:debug:
  <<: *build_template
  artifacts:
    paths:
      - game/
      - godotengine/bin/godot.x11.tools.64
  script:
    - cd godotengine
    - scons platform=x11 openssl=builtin target=debug -j2

build:gcc6:release:
  <<: *build_template
  artifacts:
    paths:
      - game/
      - godotengine/bin/godot.x11.opt.64
  script:
    - cd godotengine
    - scons platform=x11 openssl=builtin target=release tools=no -j2

build:clang:debug:
  <<: *build_template
  artifacts:
    paths:
      - game/
      - godotengine/bin/godot.x11.tools.64.llvm
  script:
    - cd godotengine
    - scons platform=x11 use_llvm=yes openssl=builtin target=debug -j2

build:clang:release:
  <<: *build_template
  artifacts:
    paths:
      - game/
      - godotengine/bin/godot.x11.opt.64.llvm
  script:
    - cd godotengine
    - scons platform=x11 use_llvm=yes openssl=builtin target=release tools=no -j2

package:gcc6:
  stage: package
  environment: staging
  dependencies:
    - build:gcc6:release
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - package_gcc6/
  script:
    - mkdir package_gcc6
    - cp godotengine/bin/godot.x11.opt.64 package_gcc6/HotelManager
    - cp -R game/* package_gcc6/

package:clang:
  stage: package
  environment: staging
  dependencies:
    - build:clang:release
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - package_clang/
  script:
    - mkdir package_clang
    - cp godotengine/bin/godot.x11.opt.64.llvm package_clang/HotelManager
    - cp -R game/* package_clang/

pages:
  before_script:
    - pacman --noconfirm -S doxygen
  stage: pages
  script:
    - cd doc && doxygen && cd ..
    - mkdir -p public/devdoc/
    - cp -R doc/html/* public/devdoc/
  artifacts:
    when: on_success
    paths:
      - public
  only:
    - master
