---
image: docker.io/nerzhul/archlinux:2016.10.01
before_script:
  - pacman --noconfirm -Sy scons libxcursor libxinerama libxrandr mesa glu alsa-lib pulseaudio freetype2 > /dev/null
# These are already included in image
# - pacman --noconfirm -S libxml2 jsoncpp curl

stages:
  - codestyle
  - build
  - package

check:codestyle:
  stage: codestyle
  environment: staging
  script:
    - .gitlab-ci/codestyle_check.sh

build:gcc6:
  stage: build
  environment: staging
  artifacts:
    when: on_success
    expire_in: 1 day
    paths:
      - game/
      - godotengine/bin/godot.x11.tools.64
  script:
    - cd godotengine
    - scons platform=x11 openssl=builtin -j2

build:clang:
  stage: build
  environment: staging
  artifacts:
    when: on_success
    expire_in: 1 day
    paths:
      - game/
      - godotengine/bin/godot.x11.tools.64.llvm
  script:
    - cd godotengine
    - scons platform=x11 use_llvm=yes openssl=builtin -j2

package:gcc6:
  stage: package
  environment: staging
  dependencies:
    - build:gcc6
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - package_gcc6/
  script:
    - mkdir package_gcc6
    - cp godotengine/bin/godot.x11.tools.64 package_gcc6/HotelManager
    - cp -R game/* package_gcc6/

package:clang:
  stage: package
  environment: staging
  dependencies:
    - build:clang
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - package_gcc6/
  script:
    - mkdir package_clang
    - cp godotengine/bin/godot.x11.tools.64.llvm package_clang/HotelManager
    - cp -R game/* package_clang/

